apiVersion: apps/v1
kind: Deployment
metadata:
  name: wav2vec2-transcriber
  labels:
    app: wav2vec2-transcriber
    project: datapipe
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wav2vec2-transcriber
  template:
    metadata:
      labels:
        app: wav2vec2-transcriber
        project: datapipe
    spec:
      imagePullSecrets:
      - name: github-registry
      volumes:
      - name: datapipe-storage
        persistentVolumeClaim:
          claimName: datapipe-storage-local
      containers:
        - name: wav2vec2-transcriber
          image: ghcr.io/ccoreilly/datapipe:0.6.4
          imagePullPolicy: IfNotPresent
          command: [ "python", "-m", "wav2vec2_transcriber" ]
          volumeMounts:
          - mountPath: /datapipe/
            name: datapipe-storage
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PG_HOST
              value: datapipe-db
            - name: API_URL
              value: http://wav2vec2-catala/recognize
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datapipe-db-secret
                  key: POSTGRES_PASSWORD
